title: ğŸŒ CentOS
content: |
  #### Official
  - [https://www.centos.org/download/](https://www.centos.org/download/)
  #### Mirrors
  - [Aliyun](https://developer.aliyun.com/mirror/centos)
    - [https://mirrors.aliyun.com/centos/](https://mirrors.aliyun.com/centos/)
  - Tencent
    - [https://mirrors.cloud.tencent.com/centos/](https://mirrors.cloud.tencent.com/centos/)
  - HUAWEI
    - [https://repo.huaweicloud.com/centos/](https://repo.huaweicloud.com/centos/)
  - 163
    - [http://mirrors.163.com/centos/](http://mirrors.163.com/centos/)
  - Souhu
    - [http://mirrors.sohu.com/centos/](http://mirrors.sohu.com/centos/)
  - åŒ—å¤§
    - [https://mirrors.pku.edu.cn/centos/](https://mirrors.pku.edu.cn/centos/)
  - æ¸…å
    - [https://mirrors.tuna.tsinghua.edu.cn/centos/](https://mirrors.tuna.tsinghua.edu.cn/centos/)
  - ä¸­ç§‘å¤§
    - [https://mirrors.ustc.edu.cn/centos/](https://mirrors.ustc.edu.cn/centos/)
  - æµ™æ±Ÿå¤§å­¦
    - [http://mirrors.zju.edu.cn/centos/](http://mirrors.zju.edu.cn/centos/)
  - å—é˜³ç†å·¥
    - [https://mirror.nyist.edu.cn/centos/](https://mirror.nyist.edu.cn/centos/)
  - å…°å·å¤§å­¦
    - [https://mirror.lzu.edu.cn/centos/](https://mirror.lzu.edu.cn/centos/)
  - ä¸œåŒ—å¤§å­¦
    - [http://mirror.neu.edu.cn/centos/](http://mirror.neu.edu.cn/centos/)
  - å¤§è¿ä¸œè½¯
    - [http://mirrors.neusoft.edu.cn/centos/](http://mirrors.neusoft.edu.cn/centos/)
  - ä¸Šæµ·äº¤é€š
    - [http://ftp.sjtu.edu.cn/centos/](http://ftp.sjtu.edu.cn/centos/)
  - åŒ—äº¬äº¤é€š
    - [https://mirror.bjtu.edu.cn/centos/](https://mirror.bjtu.edu.cn/centos/)
  - å¤§è¿ç†å·¥
    - [http://mirror.dlut.edu.cn/centos/](http://mirror.dlut.edu.cn/centos/)
  - é¦–éƒ½åœ¨çº¿
    - [http://mirrors.yun-idc.com/centos/](http://mirrors.yun-idc.com/centos/)
  - å—äº¬é‚®ç”µ
    - [http://mirrors.njupt.edu.cn/centos/](http://mirrors.njupt.edu.cn/centos/)
  - è¥¿åŒ—å†œæ—ç§‘æŠ€å¤§å­¦
    - [https://mirrors.nwsuaf.edu.cn/centos/](https://mirrors.nwsuaf.edu.cn/centos/)
  - é‡åº†å¤§å­¦
    - [https://mirrors.cqu.edu.cn/centos/](https://mirrors.cqu.edu.cn/centos/)
  - åŒ—äº¬å¤–å›½è¯­å¤§å­¦
    - [https://mirrors.bfsu.edu.cn/centos/](https://mirrors.bfsu.edu.cn/centos/)
  - å“ˆå°”æ»¨å·¥ä¸šå¤§å­¦
    - [https://mirrors.hit.edu.cn/centos/](https://mirrors.hit.edu.cn/centos/)