title: ğŸŒ‰ GNU
content: |
  #### Official
  - [https://www.gnu.org/software/octave/download](https://www.gnu.org/software/octave/download)
  #### Mirrors
  - [Aliyun](https://developer.aliyun.com/mirror/gnu)
    - [https://mirrors.aliyun.com/gnu/](https://mirrors.aliyun.com/gnu/)
  - Tencent
    - [https://mirrors.cloud.tencent.com/gnu/](https://mirrors.cloud.tencent.com/gnu/)
  - HUAWEI
    - [https://repo.huaweicloud.com/gnu/](https://repo.huaweicloud.com/gnu/)
  - æ¸…å
    - [https://mirrors.tuna.tsinghua.edu.cn/gnu/](https://mirrors.tuna.tsinghua.edu.cn/gnu/)
  - ä¸­ç§‘å¤§
    - [https://mirrors.ustc.edu.cn/gnu/](https://mirrors.ustc.edu.cn/gnu/)
  - å…°å·å¤§å­¦
    - [https://mirror.lzu.edu.cn/gnu/](https://mirror.lzu.edu.cn/gnu/)
  - åŒ—äº¬äº¤é€š
    - [https://mirror.bjtu.edu.cn/gnu/](https://mirror.bjtu.edu.cn/gnu/)