name: Latest blog post workflow
on:
  push:
    branches: # do not set multiple branches, todos might be added and then get referenced by themselves in case of a merge
      - main
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in eryajf posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          max_post_count: 6
          committer_username: "eryajf"
          committer_email: "eryajf@163.com"
          feed_list: "https://wiki.eryajf.net/rss.xml"
          template: "$newline- $randomEmoji(ğŸ’¯,ğŸ”¥,ğŸ’«,ğŸš€,ğŸŒ®,ğŸ“,ğŸ¥³,ğŸ’»,ğŸ§°,ğŸŠ,ğŸ¥°,ğŸ§,ğŸ¤“,ğŸ˜,ğŸ¥¸,ğŸ¤©,ğŸ¤—,ğŸ¤”,ğŸ«£,ğŸ¤­,ğŸ¤ ,ğŸ‘¹,ğŸ‘º,ğŸ¤¡,ğŸ¤–,ğŸƒ,ğŸ˜º,ğŸ«¶,ğŸ‘,ğŸ’ª,ğŸ’„,ğŸ‘€,ğŸ§ ,ğŸ§‘â€ğŸ«,ğŸ‘¨â€ğŸ«,ğŸ’‚,ğŸ§‘â€ğŸ’»,ğŸ¥·,ğŸ’ƒ,ğŸ•´,ğŸ’¼,ğŸ“,ğŸ»,ğŸµ,ğŸ™‰,ğŸ¦„,ğŸ¦†,ğŸ¦…,ğŸ¦,ğŸ¦£,ğŸ˜,ğŸ¦’,ğŸ¦,ğŸ,ğŸ¦©,ğŸ²,ğŸŒ,ğŸŒœ,ğŸŒ,ğŸŒˆ,ğŸŒŠ,ğŸ¬,ğŸ­,ğŸš€,ğŸš¦,â›½ï¸,ğŸ—½,ğŸ¡,ğŸŒ‹,ğŸŒ,ğŸ’¡,ğŸ•¯,ğŸªœ,ğŸ§°,âš—ï¸,ğŸ”­,ğŸª„,ğŸŠ,ğŸ‰,) [$title]($url) | $date $newline    <details><summary>å±•å¼€æè¿° ...</summary> $newline    $description $newline    </details> $newline"
      - name: Pull in eryajf posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          max_post_count: 6
          committer_username: "eryajf"
          committer_email: "eryajf@163.com"
          rand_seed: "iui"
          comment_tag_name: "iui"
          feed_list: "https://iui.su/feed"
          template: "$newline- $randomEmoji(ğŸ’¯,ğŸ”¥,ğŸ’«,ğŸš€,ğŸŒ®,ğŸ“,ğŸ¥³,ğŸ’»,ğŸ§°,ğŸŠ,ğŸ¥°,ğŸ§,ğŸ¤“,ğŸ˜,ğŸ¥¸,ğŸ¤©,ğŸ¤—,ğŸ¤”,ğŸ«£,ğŸ¤­,ğŸ¤ ,ğŸ‘¹,ğŸ‘º,ğŸ¤¡,ğŸ¤–,ğŸƒ,ğŸ˜º,ğŸ«¶,ğŸ‘,ğŸ’ª,ğŸ’„,ğŸ‘€,ğŸ§ ,ğŸ§‘â€ğŸ«,ğŸ‘¨â€ğŸ«,ğŸ’‚,ğŸ§‘â€ğŸ’»,ğŸ¥·,ğŸ’ƒ,ğŸ•´,ğŸ’¼,ğŸ“,ğŸ»,ğŸµ,ğŸ™‰,ğŸ¦„,ğŸ¦†,ğŸ¦…,ğŸ¦,ğŸ¦£,ğŸ˜,ğŸ¦’,ğŸ¦,ğŸ,ğŸ¦©,ğŸ²,ğŸŒ,ğŸŒœ,ğŸŒ,ğŸŒˆ,ğŸŒŠ,ğŸ¬,ğŸ­,ğŸš€,ğŸš¦,â›½ï¸,ğŸ—½,ğŸ¡,ğŸŒ‹,ğŸŒ,ğŸ’¡,ğŸ•¯,ğŸªœ,ğŸ§°,âš—ï¸,ğŸ”­,ğŸª„,ğŸŠ,ğŸ‰,) [$title]($url) | $date $newline    <details><summary>å±•å¼€æè¿° ...</summary> $newline    $description $newline    </details> $newline"
      - name: Pull in eryajf posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          max_post_count: 6
          committer_username: "eryajf"
          committer_email: "eryajf@163.com"
          rand_seed: "jokerps"
          comment_tag_name: "jokerps"
          feed_list: "https://www.jokerps.com/feed"
          template: "$newline- $randomEmoji(ğŸ’¯,ğŸ”¥,ğŸ’«,ğŸš€,ğŸŒ®,ğŸ“,ğŸ¥³,ğŸ’»,ğŸ§°,ğŸŠ,ğŸ¥°,ğŸ§,ğŸ¤“,ğŸ˜,ğŸ¥¸,ğŸ¤©,ğŸ¤—,ğŸ¤”,ğŸ«£,ğŸ¤­,ğŸ¤ ,ğŸ‘¹,ğŸ‘º,ğŸ¤¡,ğŸ¤–,ğŸƒ,ğŸ˜º,ğŸ«¶,ğŸ‘,ğŸ’ª,ğŸ’„,ğŸ‘€,ğŸ§ ,ğŸ§‘â€ğŸ«,ğŸ‘¨â€ğŸ«,ğŸ’‚,ğŸ§‘â€ğŸ’»,ğŸ¥·,ğŸ’ƒ,ğŸ•´,ğŸ’¼,ğŸ“,ğŸ»,ğŸµ,ğŸ™‰,ğŸ¦„,ğŸ¦†,ğŸ¦…,ğŸ¦,ğŸ¦£,ğŸ˜,ğŸ¦’,ğŸ¦,ğŸ,ğŸ¦©,ğŸ²,ğŸŒ,ğŸŒœ,ğŸŒ,ğŸŒˆ,ğŸŒŠ,ğŸ¬,ğŸ­,ğŸš€,ğŸš¦,â›½ï¸,ğŸ—½,ğŸ¡,ğŸŒ‹,ğŸŒ,ğŸ’¡,ğŸ•¯,ğŸªœ,ğŸ§°,âš—ï¸,ğŸ”­,ğŸª„,ğŸŠ,ğŸ‰,) [$title]($url) | $date $newline    <details><summary>å±•å¼€æè¿° ...</summary> $newline    $description $newline    </details> $newline"
      - name: Pull in eryajf posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          max_post_count: 6
          committer_username: "eryajf"
          committer_email: "eryajf@163.com"
          rand_seed: "v2fy"
          comment_tag_name: "v2fy"
          feed_list: "https://v2fy.com/feed/"
          template: "$newline- $randomEmoji(ğŸ’¯,ğŸ”¥,ğŸ’«,ğŸš€,ğŸŒ®,ğŸ“,ğŸ¥³,ğŸ’»,ğŸ§°,ğŸŠ,ğŸ¥°,ğŸ§,ğŸ¤“,ğŸ˜,ğŸ¥¸,ğŸ¤©,ğŸ¤—,ğŸ¤”,ğŸ«£,ğŸ¤­,ğŸ¤ ,ğŸ‘¹,ğŸ‘º,ğŸ¤¡,ğŸ¤–,ğŸƒ,ğŸ˜º,ğŸ«¶,ğŸ‘,ğŸ’ª,ğŸ’„,ğŸ‘€,ğŸ§ ,ğŸ§‘â€ğŸ«,ğŸ‘¨â€ğŸ«,ğŸ’‚,ğŸ§‘â€ğŸ’»,ğŸ¥·,ğŸ’ƒ,ğŸ•´,ğŸ’¼,ğŸ“,ğŸ»,ğŸµ,ğŸ™‰,ğŸ¦„,ğŸ¦†,ğŸ¦…,ğŸ¦,ğŸ¦£,ğŸ˜,ğŸ¦’,ğŸ¦,ğŸ,ğŸ¦©,ğŸ²,ğŸŒ,ğŸŒœ,ğŸŒ,ğŸŒˆ,ğŸŒŠ,ğŸ¬,ğŸ­,ğŸš€,ğŸš¦,â›½ï¸,ğŸ—½,ğŸ¡,ğŸŒ‹,ğŸŒ,ğŸ’¡,ğŸ•¯,ğŸªœ,ğŸ§°,âš—ï¸,ğŸ”­,ğŸª„,ğŸŠ,ğŸ‰,) [$title]($url) | $date $newline    <details><summary>å±•å¼€æè¿° ...</summary> $newline    $description $newline    </details> $newline"
      - name: Pull in eryajf posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          max_post_count: 6
          committer_username: "eryajf"
          committer_email: "eryajf@163.com"
          rand_seed: "runningcheese"
          comment_tag_name: "runningcheese"
          feed_list: "https://www.runningcheese.com/feed"
          template: "$newline- $randomEmoji(ğŸ’¯,ğŸ”¥,ğŸ’«,ğŸš€,ğŸŒ®,ğŸ“,ğŸ¥³,ğŸ’»,ğŸ§°,ğŸŠ,ğŸ¥°,ğŸ§,ğŸ¤“,ğŸ˜,ğŸ¥¸,ğŸ¤©,ğŸ¤—,ğŸ¤”,ğŸ«£,ğŸ¤­,ğŸ¤ ,ğŸ‘¹,ğŸ‘º,ğŸ¤¡,ğŸ¤–,ğŸƒ,ğŸ˜º,ğŸ«¶,ğŸ‘,ğŸ’ª,ğŸ’„,ğŸ‘€,ğŸ§ ,ğŸ§‘â€ğŸ«,ğŸ‘¨â€ğŸ«,ğŸ’‚,ğŸ§‘â€ğŸ’»,ğŸ¥·,ğŸ’ƒ,ğŸ•´,ğŸ’¼,ğŸ“,ğŸ»,ğŸµ,ğŸ™‰,ğŸ¦„,ğŸ¦†,ğŸ¦…,ğŸ¦,ğŸ¦£,ğŸ˜,ğŸ¦’,ğŸ¦,ğŸ,ğŸ¦©,ğŸ²,ğŸŒ,ğŸŒœ,ğŸŒ,ğŸŒˆ,ğŸŒŠ,ğŸ¬,ğŸ­,ğŸš€,ğŸš¦,â›½ï¸,ğŸ—½,ğŸ¡,ğŸŒ‹,ğŸŒ,ğŸ’¡,ğŸ•¯,ğŸªœ,ğŸ§°,âš—ï¸,ğŸ”­,ğŸª„,ğŸŠ,ğŸ‰,) [$title]($url) | $date $newline    <details><summary>å±•å¼€æè¿° ...</summary> $newline    $description $newline    </details> $newline"
      - name: Pull in eryajf posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          max_post_count: 6
          committer_username: "eryajf"
          committer_email: "eryajf@163.com"
          rand_seed: "greatdk"
          comment_tag_name: "greatdk"
          feed_list: "https://greatdk.com/feed"
          template: "$newline- $randomEmoji(ğŸ’¯,ğŸ”¥,ğŸ’«,ğŸš€,ğŸŒ®,ğŸ“,ğŸ¥³,ğŸ’»,ğŸ§°,ğŸŠ,ğŸ¥°,ğŸ§,ğŸ¤“,ğŸ˜,ğŸ¥¸,ğŸ¤©,ğŸ¤—,ğŸ¤”,ğŸ«£,ğŸ¤­,ğŸ¤ ,ğŸ‘¹,ğŸ‘º,ğŸ¤¡,ğŸ¤–,ğŸƒ,ğŸ˜º,ğŸ«¶,ğŸ‘,ğŸ’ª,ğŸ’„,ğŸ‘€,ğŸ§ ,ğŸ§‘â€ğŸ«,ğŸ‘¨â€ğŸ«,ğŸ’‚,ğŸ§‘â€ğŸ’»,ğŸ¥·,ğŸ’ƒ,ğŸ•´,ğŸ’¼,ğŸ“,ğŸ»,ğŸµ,ğŸ™‰,ğŸ¦„,ğŸ¦†,ğŸ¦…,ğŸ¦,ğŸ¦£,ğŸ˜,ğŸ¦’,ğŸ¦,ğŸ,ğŸ¦©,ğŸ²,ğŸŒ,ğŸŒœ,ğŸŒ,ğŸŒˆ,ğŸŒŠ,ğŸ¬,ğŸ­,ğŸš€,ğŸš¦,â›½ï¸,ğŸ—½,ğŸ¡,ğŸŒ‹,ğŸŒ,ğŸ’¡,ğŸ•¯,ğŸªœ,ğŸ§°,âš—ï¸,ğŸ”­,ğŸª„,ğŸŠ,ğŸ‰,) [$title]($url) | $date $newline    <details><summary>å±•å¼€æè¿° ...</summary> $newline    $description $newline    </details> $newline"
      - name: Pull in eryajf posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          max_post_count: 6
          committer_username: "eryajf"
          committer_email: "eryajf@163.com"
          rand_seed: "yihui"
          comment_tag_name: "yihui"
          feed_list: "https://yihui.org/cn/index.xml"
          template: "$newline- $randomEmoji(ğŸ’¯,ğŸ”¥,ğŸ’«,ğŸš€,ğŸŒ®,ğŸ“,ğŸ¥³,ğŸ’»,ğŸ§°,ğŸŠ,ğŸ¥°,ğŸ§,ğŸ¤“,ğŸ˜,ğŸ¥¸,ğŸ¤©,ğŸ¤—,ğŸ¤”,ğŸ«£,ğŸ¤­,ğŸ¤ ,ğŸ‘¹,ğŸ‘º,ğŸ¤¡,ğŸ¤–,ğŸƒ,ğŸ˜º,ğŸ«¶,ğŸ‘,ğŸ’ª,ğŸ’„,ğŸ‘€,ğŸ§ ,ğŸ§‘â€ğŸ«,ğŸ‘¨â€ğŸ«,ğŸ’‚,ğŸ§‘â€ğŸ’»,ğŸ¥·,ğŸ’ƒ,ğŸ•´,ğŸ’¼,ğŸ“,ğŸ»,ğŸµ,ğŸ™‰,ğŸ¦„,ğŸ¦†,ğŸ¦…,ğŸ¦,ğŸ¦£,ğŸ˜,ğŸ¦’,ğŸ¦,ğŸ,ğŸ¦©,ğŸ²,ğŸŒ,ğŸŒœ,ğŸŒ,ğŸŒˆ,ğŸŒŠ,ğŸ¬,ğŸ­,ğŸš€,ğŸš¦,â›½ï¸,ğŸ—½,ğŸ¡,ğŸŒ‹,ğŸŒ,ğŸ’¡,ğŸ•¯,ğŸªœ,ğŸ§°,âš—ï¸,ğŸ”­,ğŸª„,ğŸŠ,ğŸ‰,) [$title]($url) | $date $newline    <details><summary>å±•å¼€æè¿° ...</summary> $newline    $description $newline    </details> $newline"
      - name: Pull in eryajf posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          max_post_count: 6
          committer_username: "eryajf"
          committer_email: "eryajf@163.com"
          rand_seed: "v2fys"
          comment_tag_name: "v2fys"
          feed_list: "https://rsshub.v2fy.com/telegram/channel/YunPanPan"
          template: "$newline- $randomEmoji(ğŸ’¯,ğŸ”¥,ğŸ’«,ğŸš€,ğŸŒ®,ğŸ“,ğŸ¥³,ğŸ’»,ğŸ§°,ğŸŠ,ğŸ¥°,ğŸ§,ğŸ¤“,ğŸ˜,ğŸ¥¸,ğŸ¤©,ğŸ¤—,ğŸ¤”,ğŸ«£,ğŸ¤­,ğŸ¤ ,ğŸ‘¹,ğŸ‘º,ğŸ¤¡,ğŸ¤–,ğŸƒ,ğŸ˜º,ğŸ«¶,ğŸ‘,ğŸ’ª,ğŸ’„,ğŸ‘€,ğŸ§ ,ğŸ§‘â€ğŸ«,ğŸ‘¨â€ğŸ«,ğŸ’‚,ğŸ§‘â€ğŸ’»,ğŸ¥·,ğŸ’ƒ,ğŸ•´,ğŸ’¼,ğŸ“,ğŸ»,ğŸµ,ğŸ™‰,ğŸ¦„,ğŸ¦†,ğŸ¦…,ğŸ¦,ğŸ¦£,ğŸ˜,ğŸ¦’,ğŸ¦,ğŸ,ğŸ¦©,ğŸ²,ğŸŒ,ğŸŒœ,ğŸŒ,ğŸŒˆ,ğŸŒŠ,ğŸ¬,ğŸ­,ğŸš€,ğŸš¦,â›½ï¸,ğŸ—½,ğŸ¡,ğŸŒ‹,ğŸŒ,ğŸ’¡,ğŸ•¯,ğŸªœ,ğŸ§°,âš—ï¸,ğŸ”­,ğŸª„,ğŸŠ,ğŸ‰,) [$title]($url) | $date $newline    <details><summary>å±•å¼€æè¿° ...</summary> $newline    $description $newline    </details> $newline"