name: Latest blog post workflow
on:
  push:
    branches: # do not set multiple branches, todos might be added and then get referenced by themselves in case of a merge
      - main
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in eryajf posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          max_post_count: 6
          comment_tag_name: "eryajf"
          committer_username: "eryajf"
          committer_email: "eryajf@163.com"
          feed_list: "https://dq-api.azurewebsites.net/f-system/get-rss"
          template: "$newline- $randomEmoji(ğŸ’¯,ğŸ”¥,ğŸ’«,ğŸš€,ğŸŒ®,ğŸ“,ğŸ¥³,ğŸ’»,ğŸ§°,ğŸŠ,ğŸ¥°,ğŸ§,ğŸ¤“,ğŸ˜,ğŸ¥¸,ğŸ¤©,ğŸ¤—,ğŸ¤”,ğŸ«£,ğŸ¤­,ğŸ¤ ,ğŸ‘¹,ğŸ‘º,ğŸ¤¡,ğŸ¤–,ğŸƒ,ğŸ˜º,ğŸ«¶,ğŸ‘,ğŸ’ª,ğŸ’„,ğŸ‘€,ğŸ§ ,ğŸ§‘â€ğŸ«,ğŸ‘¨â€ğŸ«,ğŸ’‚,ğŸ§‘â€ğŸ’»,ğŸ¥·,ğŸ’ƒ,ğŸ•´,ğŸ’¼,ğŸ“,ğŸ»,ğŸµ,ğŸ™‰,ğŸ¦„,ğŸ¦†,ğŸ¦…,ğŸ¦,ğŸ¦£,ğŸ˜,ğŸ¦’,ğŸ¦,ğŸ,ğŸ¦©,ğŸ²,ğŸŒ,ğŸŒœ,ğŸŒ,ğŸŒˆ,ğŸŒŠ,ğŸ¬,ğŸ­,ğŸš€,ğŸš¦,â›½ï¸,ğŸ—½,ğŸ¡,ğŸŒ‹,ğŸŒ,ğŸ’¡,ğŸ•¯,ğŸªœ,ğŸ§°,âš—ï¸,ğŸ”­,ğŸª„,ğŸŠ,ğŸ‰,) [$title]($url) | $date $newline    <details><summary>å±•å¼€æè¿° ...</summary> $newline    $description $newline    </details> $newline"
      - name: Pull in eryajf posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          max_post_count: 6
          comment_tag_name: "iplaysoft"
          committer_username: "eryajf"
          committer_email: "eryajf@163.com"
          feed_list: "https://feed.iplaysoft.com/"
          template: "$newline- $randomEmoji(ğŸ’¯,ğŸ”¥,ğŸ’«,ğŸš€,ğŸŒ®,ğŸ“,ğŸ¥³,ğŸ’»,ğŸ§°,ğŸŠ,ğŸ¥°,ğŸ§,ğŸ¤“,ğŸ˜,ğŸ¥¸,ğŸ¤©,ğŸ¤—,ğŸ¤”,ğŸ«£,ğŸ¤­,ğŸ¤ ,ğŸ‘¹,ğŸ‘º,ğŸ¤¡,ğŸ¤–,ğŸƒ,ğŸ˜º,ğŸ«¶,ğŸ‘,ğŸ’ª,ğŸ’„,ğŸ‘€,ğŸ§ ,ğŸ§‘â€ğŸ«,ğŸ‘¨â€ğŸ«,ğŸ’‚,ğŸ§‘â€ğŸ’»,ğŸ¥·,ğŸ’ƒ,ğŸ•´,ğŸ’¼,ğŸ“,ğŸ»,ğŸµ,ğŸ™‰,ğŸ¦„,ğŸ¦†,ğŸ¦…,ğŸ¦,ğŸ¦£,ğŸ˜,ğŸ¦’,ğŸ¦,ğŸ,ğŸ¦©,ğŸ²,ğŸŒ,ğŸŒœ,ğŸŒ,ğŸŒˆ,ğŸŒŠ,ğŸ¬,ğŸ­,ğŸš€,ğŸš¦,â›½ï¸,ğŸ—½,ğŸ¡,ğŸŒ‹,ğŸŒ,ğŸ’¡,ğŸ•¯,ğŸªœ,ğŸ§°,âš—ï¸,ğŸ”­,ğŸª„,ğŸŠ,ğŸ‰,) [$title]($url) | $date $newline    <details><summary>å±•å¼€æè¿° ...</summary> $newline    $description $newline    </details> $newline"
      - name: Pull in eryajf posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          max_post_count: 6
          comment_tag_name: "gcores"
          committer_username: "eryajf"
          committer_email: "eryajf@163.com"
          feed_list: "https://www.gcores.com/rss"
          template: "$newline- $randomEmoji(ğŸ’¯,ğŸ”¥,ğŸ’«,ğŸš€,ğŸŒ®,ğŸ“,ğŸ¥³,ğŸ’»,ğŸ§°,ğŸŠ,ğŸ¥°,ğŸ§,ğŸ¤“,ğŸ˜,ğŸ¥¸,ğŸ¤©,ğŸ¤—,ğŸ¤”,ğŸ«£,ğŸ¤­,ğŸ¤ ,ğŸ‘¹,ğŸ‘º,ğŸ¤¡,ğŸ¤–,ğŸƒ,ğŸ˜º,ğŸ«¶,ğŸ‘,ğŸ’ª,ğŸ’„,ğŸ‘€,ğŸ§ ,ğŸ§‘â€ğŸ«,ğŸ‘¨â€ğŸ«,ğŸ’‚,ğŸ§‘â€ğŸ’»,ğŸ¥·,ğŸ’ƒ,ğŸ•´,ğŸ’¼,ğŸ“,ğŸ»,ğŸµ,ğŸ™‰,ğŸ¦„,ğŸ¦†,ğŸ¦…,ğŸ¦,ğŸ¦£,ğŸ˜,ğŸ¦’,ğŸ¦,ğŸ,ğŸ¦©,ğŸ²,ğŸŒ,ğŸŒœ,ğŸŒ,ğŸŒˆ,ğŸŒŠ,ğŸ¬,ğŸ­,ğŸš€,ğŸš¦,â›½ï¸,ğŸ—½,ğŸ¡,ğŸŒ‹,ğŸŒ,ğŸ’¡,ğŸ•¯,ğŸªœ,ğŸ§°,âš—ï¸,ğŸ”­,ğŸª„,ğŸŠ,ğŸ‰,) [$title]($url) | $date $newline    <details><summary>å±•å¼€æè¿° ...</summary> $newline    $description $newline    </details> $newline"
      - name: Pull in eryajf posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          max_post_count: 6
          comment_tag_name: "jandan"
          committer_username: "eryajf"
          committer_email: "eryajf@163.com"
          feed_list: "http://jandan.net/feed"
          template: "$newline- $randomEmoji(ğŸ’¯,ğŸ”¥,ğŸ’«,ğŸš€,ğŸŒ®,ğŸ“,ğŸ¥³,ğŸ’»,ğŸ§°,ğŸŠ,ğŸ¥°,ğŸ§,ğŸ¤“,ğŸ˜,ğŸ¥¸,ğŸ¤©,ğŸ¤—,ğŸ¤”,ğŸ«£,ğŸ¤­,ğŸ¤ ,ğŸ‘¹,ğŸ‘º,ğŸ¤¡,ğŸ¤–,ğŸƒ,ğŸ˜º,ğŸ«¶,ğŸ‘,ğŸ’ª,ğŸ’„,ğŸ‘€,ğŸ§ ,ğŸ§‘â€ğŸ«,ğŸ‘¨â€ğŸ«,ğŸ’‚,ğŸ§‘â€ğŸ’»,ğŸ¥·,ğŸ’ƒ,ğŸ•´,ğŸ’¼,ğŸ“,ğŸ»,ğŸµ,ğŸ™‰,ğŸ¦„,ğŸ¦†,ğŸ¦…,ğŸ¦,ğŸ¦£,ğŸ˜,ğŸ¦’,ğŸ¦,ğŸ,ğŸ¦©,ğŸ²,ğŸŒ,ğŸŒœ,ğŸŒ,ğŸŒˆ,ğŸŒŠ,ğŸ¬,ğŸ­,ğŸš€,ğŸš¦,â›½ï¸,ğŸ—½,ğŸ¡,ğŸŒ‹,ğŸŒ,ğŸ’¡,ğŸ•¯,ğŸªœ,ğŸ§°,âš—ï¸,ğŸ”­,ğŸª„,ğŸŠ,ğŸ‰,) [$title]($url) | $date $newline    <details><summary>å±•å¼€æè¿° ...</summary> $newline    $description $newline    </details> $newline"
      - name: Pull in eryajf posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          max_post_count: 6
          comment_tag_name: "cnbeta"
          committer_username: "eryajf"
          committer_email: "eryajf@163.com"
          feed_list: "https://rss.cnbeta.com/"
          template: "$newline- $randomEmoji(ğŸ’¯,ğŸ”¥,ğŸ’«,ğŸš€,ğŸŒ®,ğŸ“,ğŸ¥³,ğŸ’»,ğŸ§°,ğŸŠ,ğŸ¥°,ğŸ§,ğŸ¤“,ğŸ˜,ğŸ¥¸,ğŸ¤©,ğŸ¤—,ğŸ¤”,ğŸ«£,ğŸ¤­,ğŸ¤ ,ğŸ‘¹,ğŸ‘º,ğŸ¤¡,ğŸ¤–,ğŸƒ,ğŸ˜º,ğŸ«¶,ğŸ‘,ğŸ’ª,ğŸ’„,ğŸ‘€,ğŸ§ ,ğŸ§‘â€ğŸ«,ğŸ‘¨â€ğŸ«,ğŸ’‚,ğŸ§‘â€ğŸ’»,ğŸ¥·,ğŸ’ƒ,ğŸ•´,ğŸ’¼,ğŸ“,ğŸ»,ğŸµ,ğŸ™‰,ğŸ¦„,ğŸ¦†,ğŸ¦…,ğŸ¦,ğŸ¦£,ğŸ˜,ğŸ¦’,ğŸ¦,ğŸ,ğŸ¦©,ğŸ²,ğŸŒ,ğŸŒœ,ğŸŒ,ğŸŒˆ,ğŸŒŠ,ğŸ¬,ğŸ­,ğŸš€,ğŸš¦,â›½ï¸,ğŸ—½,ğŸ¡,ğŸŒ‹,ğŸŒ,ğŸ’¡,ğŸ•¯,ğŸªœ,ğŸ§°,âš—ï¸,ğŸ”­,ğŸª„,ğŸŠ,ğŸ‰,) [$title]($url) | $date $newline    <details><summary>å±•å¼€æè¿° ...</summary> $newline    $description $newline    </details> $newline"
      - name: Pull in eryajf posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          max_post_count: 6
          comment_tag_name: "photoworld"
          committer_username: "eryajf"
          committer_email: "eryajf@163.com"
          feed_list: "http://www.photoworld.com.cn/feed"
          template: "$newline- $randomEmoji(ğŸ’¯,ğŸ”¥,ğŸ’«,ğŸš€,ğŸŒ®,ğŸ“,ğŸ¥³,ğŸ’»,ğŸ§°,ğŸŠ,ğŸ¥°,ğŸ§,ğŸ¤“,ğŸ˜,ğŸ¥¸,ğŸ¤©,ğŸ¤—,ğŸ¤”,ğŸ«£,ğŸ¤­,ğŸ¤ ,ğŸ‘¹,ğŸ‘º,ğŸ¤¡,ğŸ¤–,ğŸƒ,ğŸ˜º,ğŸ«¶,ğŸ‘,ğŸ’ª,ğŸ’„,ğŸ‘€,ğŸ§ ,ğŸ§‘â€ğŸ«,ğŸ‘¨â€ğŸ«,ğŸ’‚,ğŸ§‘â€ğŸ’»,ğŸ¥·,ğŸ’ƒ,ğŸ•´,ğŸ’¼,ğŸ“,ğŸ»,ğŸµ,ğŸ™‰,ğŸ¦„,ğŸ¦†,ğŸ¦…,ğŸ¦,ğŸ¦£,ğŸ˜,ğŸ¦’,ğŸ¦,ğŸ,ğŸ¦©,ğŸ²,ğŸŒ,ğŸŒœ,ğŸŒ,ğŸŒˆ,ğŸŒŠ,ğŸ¬,ğŸ­,ğŸš€,ğŸš¦,â›½ï¸,ğŸ—½,ğŸ¡,ğŸŒ‹,ğŸŒ,ğŸ’¡,ğŸ•¯,ğŸªœ,ğŸ§°,âš—ï¸,ğŸ”­,ğŸª„,ğŸŠ,ğŸ‰,) [$title]($url) | $date $newline    <details><summary>å±•å¼€æè¿° ...</summary> $newline    $description $newline    </details> $newline"
      - name: Pull in eryajf posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          max_post_count: 6
          comment_tag_name: "chanpin100"
          committer_username: "eryajf"
          committer_email: "eryajf@163.com"
          feed_list: "http://www.chanpin100.com/feed"
          template: "$newline- $randomEmoji(ğŸ’¯,ğŸ”¥,ğŸ’«,ğŸš€,ğŸŒ®,ğŸ“,ğŸ¥³,ğŸ’»,ğŸ§°,ğŸŠ,ğŸ¥°,ğŸ§,ğŸ¤“,ğŸ˜,ğŸ¥¸,ğŸ¤©,ğŸ¤—,ğŸ¤”,ğŸ«£,ğŸ¤­,ğŸ¤ ,ğŸ‘¹,ğŸ‘º,ğŸ¤¡,ğŸ¤–,ğŸƒ,ğŸ˜º,ğŸ«¶,ğŸ‘,ğŸ’ª,ğŸ’„,ğŸ‘€,ğŸ§ ,ğŸ§‘â€ğŸ«,ğŸ‘¨â€ğŸ«,ğŸ’‚,ğŸ§‘â€ğŸ’»,ğŸ¥·,ğŸ’ƒ,ğŸ•´,ğŸ’¼,ğŸ“,ğŸ»,ğŸµ,ğŸ™‰,ğŸ¦„,ğŸ¦†,ğŸ¦…,ğŸ¦,ğŸ¦£,ğŸ˜,ğŸ¦’,ğŸ¦,ğŸ,ğŸ¦©,ğŸ²,ğŸŒ,ğŸŒœ,ğŸŒ,ğŸŒˆ,ğŸŒŠ,ğŸ¬,ğŸ­,ğŸš€,ğŸš¦,â›½ï¸,ğŸ—½,ğŸ¡,ğŸŒ‹,ğŸŒ,ğŸ’¡,ğŸ•¯,ğŸªœ,ğŸ§°,âš—ï¸,ğŸ”­,ğŸª„,ğŸŠ,ğŸ‰,) [$title]($url) | $date $newline    <details><summary>å±•å¼€æè¿° ...</summary> $newline    $description $newline    </details> $newline"
      - name: Pull in eryajf posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          max_post_count: 6
          comment_tag_name: "woshipm"
          committer_username: "eryajf"
          committer_email: "eryajf@163.com"
          feed_list: "https://www.woshipm.com/feed"
          template: "$newline- $randomEmoji(ğŸ’¯,ğŸ”¥,ğŸ’«,ğŸš€,ğŸŒ®,ğŸ“,ğŸ¥³,ğŸ’»,ğŸ§°,ğŸŠ,ğŸ¥°,ğŸ§,ğŸ¤“,ğŸ˜,ğŸ¥¸,ğŸ¤©,ğŸ¤—,ğŸ¤”,ğŸ«£,ğŸ¤­,ğŸ¤ ,ğŸ‘¹,ğŸ‘º,ğŸ¤¡,ğŸ¤–,ğŸƒ,ğŸ˜º,ğŸ«¶,ğŸ‘,ğŸ’ª,ğŸ’„,ğŸ‘€,ğŸ§ ,ğŸ§‘â€ğŸ«,ğŸ‘¨â€ğŸ«,ğŸ’‚,ğŸ§‘â€ğŸ’»,ğŸ¥·,ğŸ’ƒ,ğŸ•´,ğŸ’¼,ğŸ“,ğŸ»,ğŸµ,ğŸ™‰,ğŸ¦„,ğŸ¦†,ğŸ¦…,ğŸ¦,ğŸ¦£,ğŸ˜,ğŸ¦’,ğŸ¦,ğŸ,ğŸ¦©,ğŸ²,ğŸŒ,ğŸŒœ,ğŸŒ,ğŸŒˆ,ğŸŒŠ,ğŸ¬,ğŸ­,ğŸš€,ğŸš¦,â›½ï¸,ğŸ—½,ğŸ¡,ğŸŒ‹,ğŸŒ,ğŸ’¡,ğŸ•¯,ğŸªœ,ğŸ§°,âš—ï¸,ğŸ”­,ğŸª„,ğŸŠ,ğŸ‰,) [$title]($url) | $date $newline    <details><summary>å±•å¼€æè¿° ...</summary> $newline    $description $newline    </details> $newline"
      - name: Pull in eryajf posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          max_post_count: 6
          comment_tag_name: "freebuf"
          committer_username: "eryajf"
          committer_email: "eryajf@163.com"
          feed_list: "https://www.freebuf.com/feed"
          template: "$newline- $randomEmoji(ğŸ’¯,ğŸ”¥,ğŸ’«,ğŸš€,ğŸŒ®,ğŸ“,ğŸ¥³,ğŸ’»,ğŸ§°,ğŸŠ,ğŸ¥°,ğŸ§,ğŸ¤“,ğŸ˜,ğŸ¥¸,ğŸ¤©,ğŸ¤—,ğŸ¤”,ğŸ«£,ğŸ¤­,ğŸ¤ ,ğŸ‘¹,ğŸ‘º,ğŸ¤¡,ğŸ¤–,ğŸƒ,ğŸ˜º,ğŸ«¶,ğŸ‘,ğŸ’ª,ğŸ’„,ğŸ‘€,ğŸ§ ,ğŸ§‘â€ğŸ«,ğŸ‘¨â€ğŸ«,ğŸ’‚,ğŸ§‘â€ğŸ’»,ğŸ¥·,ğŸ’ƒ,ğŸ•´,ğŸ’¼,ğŸ“,ğŸ»,ğŸµ,ğŸ™‰,ğŸ¦„,ğŸ¦†,ğŸ¦…,ğŸ¦,ğŸ¦£,ğŸ˜,ğŸ¦’,ğŸ¦,ğŸ,ğŸ¦©,ğŸ²,ğŸŒ,ğŸŒœ,ğŸŒ,ğŸŒˆ,ğŸŒŠ,ğŸ¬,ğŸ­,ğŸš€,ğŸš¦,â›½ï¸,ğŸ—½,ğŸ¡,ğŸŒ‹,ğŸŒ,ğŸ’¡,ğŸ•¯,ğŸªœ,ğŸ§°,âš—ï¸,ğŸ”­,ğŸª„,ğŸŠ,ğŸ‰,) [$title]($url) | $date $newline    <details><summary>å±•å¼€æè¿° ...</summary> $newline    $description $newline    </details> $newline"
      - name: Pull in eryajf posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          max_post_count: 6
          comment_tag_name: "mac52ipod"
          committer_username: "eryajf"
          committer_email: "eryajf@163.com"
          feed_list: "http://www.mac52ipod.cn/feed.php"
          template: "$newline- $randomEmoji(ğŸ’¯,ğŸ”¥,ğŸ’«,ğŸš€,ğŸŒ®,ğŸ“,ğŸ¥³,ğŸ’»,ğŸ§°,ğŸŠ,ğŸ¥°,ğŸ§,ğŸ¤“,ğŸ˜,ğŸ¥¸,ğŸ¤©,ğŸ¤—,ğŸ¤”,ğŸ«£,ğŸ¤­,ğŸ¤ ,ğŸ‘¹,ğŸ‘º,ğŸ¤¡,ğŸ¤–,ğŸƒ,ğŸ˜º,ğŸ«¶,ğŸ‘,ğŸ’ª,ğŸ’„,ğŸ‘€,ğŸ§ ,ğŸ§‘â€ğŸ«,ğŸ‘¨â€ğŸ«,ğŸ’‚,ğŸ§‘â€ğŸ’»,ğŸ¥·,ğŸ’ƒ,ğŸ•´,ğŸ’¼,ğŸ“,ğŸ»,ğŸµ,ğŸ™‰,ğŸ¦„,ğŸ¦†,ğŸ¦…,ğŸ¦,ğŸ¦£,ğŸ˜,ğŸ¦’,ğŸ¦,ğŸ,ğŸ¦©,ğŸ²,ğŸŒ,ğŸŒœ,ğŸŒ,ğŸŒˆ,ğŸŒŠ,ğŸ¬,ğŸ­,ğŸš€,ğŸš¦,â›½ï¸,ğŸ—½,ğŸ¡,ğŸŒ‹,ğŸŒ,ğŸ’¡,ğŸ•¯,ğŸªœ,ğŸ§°,âš—ï¸,ğŸ”­,ğŸª„,ğŸŠ,ğŸ‰,) [$title]($url) | $date $newline    <details><summary>å±•å¼€æè¿° ...</summary> $newline    $description $newline    </details> $newline"
      - name: Pull in eryajf posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          max_post_count: 6
          comment_tag_name: "xinquji"
          committer_username: "eryajf"
          committer_email: "eryajf@163.com"
          feed_list: "https://xinquji.com/rss"
          template: "$newline- $randomEmoji(ğŸ’¯,ğŸ”¥,ğŸ’«,ğŸš€,ğŸŒ®,ğŸ“,ğŸ¥³,ğŸ’»,ğŸ§°,ğŸŠ,ğŸ¥°,ğŸ§,ğŸ¤“,ğŸ˜,ğŸ¥¸,ğŸ¤©,ğŸ¤—,ğŸ¤”,ğŸ«£,ğŸ¤­,ğŸ¤ ,ğŸ‘¹,ğŸ‘º,ğŸ¤¡,ğŸ¤–,ğŸƒ,ğŸ˜º,ğŸ«¶,ğŸ‘,ğŸ’ª,ğŸ’„,ğŸ‘€,ğŸ§ ,ğŸ§‘â€ğŸ«,ğŸ‘¨â€ğŸ«,ğŸ’‚,ğŸ§‘â€ğŸ’»,ğŸ¥·,ğŸ’ƒ,ğŸ•´,ğŸ’¼,ğŸ“,ğŸ»,ğŸµ,ğŸ™‰,ğŸ¦„,ğŸ¦†,ğŸ¦…,ğŸ¦,ğŸ¦£,ğŸ˜,ğŸ¦’,ğŸ¦,ğŸ,ğŸ¦©,ğŸ²,ğŸŒ,ğŸŒœ,ğŸŒ,ğŸŒˆ,ğŸŒŠ,ğŸ¬,ğŸ­,ğŸš€,ğŸš¦,â›½ï¸,ğŸ—½,ğŸ¡,ğŸŒ‹,ğŸŒ,ğŸ’¡,ğŸ•¯,ğŸªœ,ğŸ§°,âš—ï¸,ğŸ”­,ğŸª„,ğŸŠ,ğŸ‰,) [$title]($url) | $date $newline    <details><summary>å±•å¼€æè¿° ...</summary> $newline    $description $newline    </details> $newline"
      - name: Pull in eryajf posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          max_post_count: 6
          comment_tag_name: "xclient"
          committer_username: "eryajf"
          committer_email: "eryajf@163.com"
          feed_list: "https://xclient.info/feed/"
          template: "$newline- $randomEmoji(ğŸ’¯,ğŸ”¥,ğŸ’«,ğŸš€,ğŸŒ®,ğŸ“,ğŸ¥³,ğŸ’»,ğŸ§°,ğŸŠ,ğŸ¥°,ğŸ§,ğŸ¤“,ğŸ˜,ğŸ¥¸,ğŸ¤©,ğŸ¤—,ğŸ¤”,ğŸ«£,ğŸ¤­,ğŸ¤ ,ğŸ‘¹,ğŸ‘º,ğŸ¤¡,ğŸ¤–,ğŸƒ,ğŸ˜º,ğŸ«¶,ğŸ‘,ğŸ’ª,ğŸ’„,ğŸ‘€,ğŸ§ ,ğŸ§‘â€ğŸ«,ğŸ‘¨â€ğŸ«,ğŸ’‚,ğŸ§‘â€ğŸ’»,ğŸ¥·,ğŸ’ƒ,ğŸ•´,ğŸ’¼,ğŸ“,ğŸ»,ğŸµ,ğŸ™‰,ğŸ¦„,ğŸ¦†,ğŸ¦…,ğŸ¦,ğŸ¦£,ğŸ˜,ğŸ¦’,ğŸ¦,ğŸ,ğŸ¦©,ğŸ²,ğŸŒ,ğŸŒœ,ğŸŒ,ğŸŒˆ,ğŸŒŠ,ğŸ¬,ğŸ­,ğŸš€,ğŸš¦,â›½ï¸,ğŸ—½,ğŸ¡,ğŸŒ‹,ğŸŒ,ğŸ’¡,ğŸ•¯,ğŸªœ,ğŸ§°,âš—ï¸,ğŸ”­,ğŸª„,ğŸŠ,ğŸ‰,) [$title]($url) | $date $newline    <details><summary>å±•å¼€æè¿° ...</summary> $newline    $description $newline    </details> $newline"
      - name: Pull in eryajf posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          max_post_count: 6
          comment_tag_name: "toodaylab"
          committer_username: "eryajf"
          committer_email: "eryajf@163.com"
          feed_list: "http://www.toodaylab.com/feed"
          template: "$newline- $randomEmoji(ğŸ’¯,ğŸ”¥,ğŸ’«,ğŸš€,ğŸŒ®,ğŸ“,ğŸ¥³,ğŸ’»,ğŸ§°,ğŸŠ,ğŸ¥°,ğŸ§,ğŸ¤“,ğŸ˜,ğŸ¥¸,ğŸ¤©,ğŸ¤—,ğŸ¤”,ğŸ«£,ğŸ¤­,ğŸ¤ ,ğŸ‘¹,ğŸ‘º,ğŸ¤¡,ğŸ¤–,ğŸƒ,ğŸ˜º,ğŸ«¶,ğŸ‘,ğŸ’ª,ğŸ’„,ğŸ‘€,ğŸ§ ,ğŸ§‘â€ğŸ«,ğŸ‘¨â€ğŸ«,ğŸ’‚,ğŸ§‘â€ğŸ’»,ğŸ¥·,ğŸ’ƒ,ğŸ•´,ğŸ’¼,ğŸ“,ğŸ»,ğŸµ,ğŸ™‰,ğŸ¦„,ğŸ¦†,ğŸ¦…,ğŸ¦,ğŸ¦£,ğŸ˜,ğŸ¦’,ğŸ¦,ğŸ,ğŸ¦©,ğŸ²,ğŸŒ,ğŸŒœ,ğŸŒ,ğŸŒˆ,ğŸŒŠ,ğŸ¬,ğŸ­,ğŸš€,ğŸš¦,â›½ï¸,ğŸ—½,ğŸ¡,ğŸŒ‹,ğŸŒ,ğŸ’¡,ğŸ•¯,ğŸªœ,ğŸ§°,âš—ï¸,ğŸ”­,ğŸª„,ğŸŠ,ğŸ‰,) [$title]($url) | $date $newline    <details><summary>å±•å¼€æè¿° ...</summary> $newline    $description $newline    </details> $newline"
      - name: Pull in eryajf posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          max_post_count: 6
          comment_tag_name: "alloyteam"
          committer_username: "eryajf"
          committer_email: "eryajf@163.com"
          feed_list: "http://www.alloyteam.com/feed/"
          template: "$newline- $randomEmoji(ğŸ’¯,ğŸ”¥,ğŸ’«,ğŸš€,ğŸŒ®,ğŸ“,ğŸ¥³,ğŸ’»,ğŸ§°,ğŸŠ,ğŸ¥°,ğŸ§,ğŸ¤“,ğŸ˜,ğŸ¥¸,ğŸ¤©,ğŸ¤—,ğŸ¤”,ğŸ«£,ğŸ¤­,ğŸ¤ ,ğŸ‘¹,ğŸ‘º,ğŸ¤¡,ğŸ¤–,ğŸƒ,ğŸ˜º,ğŸ«¶,ğŸ‘,ğŸ’ª,ğŸ’„,ğŸ‘€,ğŸ§ ,ğŸ§‘â€ğŸ«,ğŸ‘¨â€ğŸ«,ğŸ’‚,ğŸ§‘â€ğŸ’»,ğŸ¥·,ğŸ’ƒ,ğŸ•´,ğŸ’¼,ğŸ“,ğŸ»,ğŸµ,ğŸ™‰,ğŸ¦„,ğŸ¦†,ğŸ¦…,ğŸ¦,ğŸ¦£,ğŸ˜,ğŸ¦’,ğŸ¦,ğŸ,ğŸ¦©,ğŸ²,ğŸŒ,ğŸŒœ,ğŸŒ,ğŸŒˆ,ğŸŒŠ,ğŸ¬,ğŸ­,ğŸš€,ğŸš¦,â›½ï¸,ğŸ—½,ğŸ¡,ğŸŒ‹,ğŸŒ,ğŸ’¡,ğŸ•¯,ğŸªœ,ğŸ§°,âš—ï¸,ğŸ”­,ğŸª„,ğŸŠ,ğŸ‰,) [$title]($url) | $date $newline    <details><summary>å±•å¼€æè¿° ...</summary> $newline    $description $newline    </details> $newline"
      - name: Pull in eryajf posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          max_post_count: 6
          comment_tag_name: "huoding"
          committer_username: "eryajf"
          committer_email: "eryajf@163.com"
          feed_list: "https://blog.huoding.com/feed"
          template: "$newline- $randomEmoji(ğŸ’¯,ğŸ”¥,ğŸ’«,ğŸš€,ğŸŒ®,ğŸ“,ğŸ¥³,ğŸ’»,ğŸ§°,ğŸŠ,ğŸ¥°,ğŸ§,ğŸ¤“,ğŸ˜,ğŸ¥¸,ğŸ¤©,ğŸ¤—,ğŸ¤”,ğŸ«£,ğŸ¤­,ğŸ¤ ,ğŸ‘¹,ğŸ‘º,ğŸ¤¡,ğŸ¤–,ğŸƒ,ğŸ˜º,ğŸ«¶,ğŸ‘,ğŸ’ª,ğŸ’„,ğŸ‘€,ğŸ§ ,ğŸ§‘â€ğŸ«,ğŸ‘¨â€ğŸ«,ğŸ’‚,ğŸ§‘â€ğŸ’»,ğŸ¥·,ğŸ’ƒ,ğŸ•´,ğŸ’¼,ğŸ“,ğŸ»,ğŸµ,ğŸ™‰,ğŸ¦„,ğŸ¦†,ğŸ¦…,ğŸ¦,ğŸ¦£,ğŸ˜,ğŸ¦’,ğŸ¦,ğŸ,ğŸ¦©,ğŸ²,ğŸŒ,ğŸŒœ,ğŸŒ,ğŸŒˆ,ğŸŒŠ,ğŸ¬,ğŸ­,ğŸš€,ğŸš¦,â›½ï¸,ğŸ—½,ğŸ¡,ğŸŒ‹,ğŸŒ,ğŸ’¡,ğŸ•¯,ğŸªœ,ğŸ§°,âš—ï¸,ğŸ”­,ğŸª„,ğŸŠ,ğŸ‰,) [$title]($url) | $date $newline    <details><summary>å±•å¼€æè¿° ...</summary> $newline    $description $newline    </details> $newline"
